services:
  eureka-server:
    build: eureka-sv/eureka-sv
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend-cities-hotels
  config-server:
    build: config-server/config-server
    container_name: config-server
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - backend-cities-hotels

  cities-service:
    build: cities-service/cities-service
    container_name: cities-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
    networks:
      - backend-cities-hotels
      
networks:
  backend-cities-hotels: