spring:
  application:
    name: cities-service
  cloud:
      config:
        uri: http://config-server:8081

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
      #defaultZone: http://localhost:8761/eureka

