version: '2.1'

services:
  eureka-server:
    build: eureka-sv/eureka-sv #donde esta el dockerfile de tu proyecto eureka
    ports:
      - "8761:8761"
    networks:
      - 'userpost-network'
      
  users-service:
    build: users-service/users-service
    ports:
      - "8083:8083"
    networks:
      - 'userpost-network'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/users_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  posts-service:
    build: posts-service
    mem_limit: 512m
    ports:
      - "8084:8084"
    networks:
      - 'userpost-network'

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_service
    volumes:
      - mysql-vol:/mysql

volumes:
  mysql-vol:
    
  
networks:
  userpost-network: